apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  template:
    metadata:
      labels:
       name: app-pod
    spec:
      containers:
        - name: container-loja
          image: rafanercessian/aplicacao-loja:v1
          ports:
            - containerPort: 80